# Generated by Django 4.2.7 on 2023-11-05 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0005_articles_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_owners', to='database.articles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Books_request',
                'verbose_name_plural': 'Books_requests',
                'unique_together': {('user', 'book')},
            },
        ),
    ]
