# Generated by Django 4.2.7 on 2023-11-05 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books_request',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='books_request',
            name='date_withdrawal',
            field=models.DateTimeField(default='1000-01-01 00:00:00'),
        ),
        migrations.AddField(
            model_name='books_request',
            name='status',
            field=models.CharField(default='Processing', max_length=50, verbose_name='status'),
        ),
    ]
