# Generated by Django 4.2.7 on 2023-11-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_request', '0002_books_request_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books_request',
            name='date_checked_by_admin',
            field=models.DateTimeField(default='1000-01-01 00:00:00'),
        ),
    ]
