# Generated by Django 4.2.7 on 2023-11-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'article', 'verbose_name_plural': 'articles'},
        ),
    ]
