# Generated by Django 4.2.7 on 2023-11-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_articles_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='date',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='full_text',
        ),
        migrations.AddField(
            model_name='articles',
            name='autor',
            field=models.CharField(default='Nonename', max_length=50, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='articles',
            name='full_text_pdf',
            field=models.FileField(default='', upload_to='articles_pdfs/', verbose_name='Full_text_pdf'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='anons',
            field=models.CharField(default='None', max_length=250, verbose_name='Anons'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(default='Good', max_length=50, verbose_name='Name'),
        ),
    ]
