# Generated by Django 4.2.7 on 2023-11-16 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0005_articles_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='anons',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='full_text_pdf',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='quantity',
        ),
        migrations.AddField(
            model_name='articles',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
